# Generated by Django 5.2.8 on 2026-01-14 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_code',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Код подтверждения'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Банковская карта'), ('email', 'Оплата по email'), ('none', 'Не выбран')], default='none', max_length=20, verbose_name='Способ оплаты'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Ожидает оплаты'), ('completed', 'Оплачено'), ('failed', 'Ошибка оплаты')], default='pending', max_length=20, verbose_name='Статус оплаты'),
        ),
    ]
